image: openjdk:12-alpine

stages:
  - deploy-prod
  - deploy-dev

deploy-prod:
  stage: deploy-prod
  script:
    - ./gradlew clean jar
    - curl -LX POST autocd.cloudiety.de -F token=utTEfVmghCnMfq99MZ4W -F autocd=@build/libs/AutoCD-1.0.jar
  only:
    - master

deploy-dev:
  stage: deploy-dev
  script:
    - ./gradlew clean jar
    - curl -LX POST autocd-dev.cloudiety.de -F token=W8LpB6L8fkWZFwACtKcv -F autocd=@build/libs/AutoCD-1.0.jar
  only:
    - develop